# Generated by Django 3.2.9 on 2021-11-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ВС')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ангара')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название агрегата')),
                ('slug', models.SlugField()),
                ('parttype', models.IntegerField(verbose_name='Код запчасти')),
                ('repairdate', models.DateField(default=0, verbose_name='Дата последнего ремонта')),
                ('controldate', models.DateField(default=0, verbose_name='Дата последнего обслуживания')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.aircraft', verbose_name='ВС')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.garage', verbose_name='Ангар')),
            ],
        ),
        migrations.AddField(
            model_name='aircraft',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.garage', verbose_name='Ангар'),
        ),
    ]
