# Generated by Django 3.2.9 on 2021-11-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211121_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='type',
            field=models.CharField(default='пусто', max_length=255, verbose_name='Тип ВС'),
        ),
    ]
