# Generated by Django 3.2.9 on 2021-11-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_unit_garage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='slug',
        ),
    ]
