# Generated by Django 3.2.9 on 2021-12-10 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_unit_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='time_to_control',
            field=models.IntegerField(default=1, verbose_name='Интервал обслуживания (дни)'),
        ),
        migrations.AddField(
            model_name='unit',
            name='time_to_fix',
            field=models.IntegerField(default=1, verbose_name='Интервал ремонта (дни)'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcr', to='mainapp.garage', verbose_name='Ангар'),
        ),
    ]
